<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <AssemblyName>Kumori.StarDB.Builder</AssemblyName>
    <RootNamespace>Kumori.StarDB.Builder</RootNamespace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\osu.Game.Rulesets.Kumori\osu.Game.Rulesets.Kumori.csproj" />
  </ItemGroup>
</Project>
